/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPrivateERC721URIStorage__factory } from "./IPrivateERC721URIStorage__factory";
export { PrivateERC721URIStorage__factory } from "./PrivateERC721URIStorage__factory";
