/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CAPIBARA__factory } from "./CAPIBARA__factory";
export { CAPIBARA_FIXED__factory } from "./CAPIBARA_FIXED__factory";
