/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mpcInterfaceSol from "./MpcInterface.sol";
export { MpcCore__factory } from "./MpcCore__factory";
