/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export declare namespace CheckedArithmeticWithOverflowBitTestsContract {
  export type Check16Struct = {
    res16_16: BigNumberish;
    res8_16: BigNumberish;
    res16_8: BigNumberish;
  };

  export type Check16StructOutput = [
    res16_16: bigint,
    res8_16: bigint,
    res16_8: bigint
  ] & { res16_16: bigint; res8_16: bigint; res16_8: bigint };

  export type Check32Struct = {
    res32_32: BigNumberish;
    res8_32: BigNumberish;
    res32_8: BigNumberish;
    res16_32: BigNumberish;
    res32_16: BigNumberish;
  };

  export type Check32StructOutput = [
    res32_32: bigint,
    res8_32: bigint,
    res32_8: bigint,
    res16_32: bigint,
    res32_16: bigint
  ] & {
    res32_32: bigint;
    res8_32: bigint;
    res32_8: bigint;
    res16_32: bigint;
    res32_16: bigint;
  };

  export type Check64Struct = {
    res64_64: BigNumberish;
    res8_64: BigNumberish;
    res64_8: BigNumberish;
    res16_64: BigNumberish;
    res64_16: BigNumberish;
    res32_64: BigNumberish;
    res64_32: BigNumberish;
  };

  export type Check64StructOutput = [
    res64_64: bigint,
    res8_64: bigint,
    res64_8: bigint,
    res16_64: bigint,
    res64_16: bigint,
    res32_64: bigint,
    res64_32: bigint
  ] & {
    res64_64: bigint;
    res8_64: bigint;
    res64_8: bigint;
    res16_64: bigint;
    res64_16: bigint;
    res32_64: bigint;
    res64_32: bigint;
  };

  export type AllGTCastingValuesStruct = {
    a8_s: BigNumberish;
    b8_s: BigNumberish;
    a16_s: BigNumberish;
    b16_s: BigNumberish;
    a32_s: BigNumberish;
    b32_s: BigNumberish;
    a64_s: BigNumberish;
    b64_s: BigNumberish;
  };

  export type AllGTCastingValuesStructOutput = [
    a8_s: bigint,
    b8_s: bigint,
    a16_s: bigint,
    b16_s: bigint,
    a32_s: bigint,
    b32_s: bigint,
    a64_s: bigint,
    b64_s: bigint
  ] & {
    a8_s: bigint;
    b8_s: bigint;
    a16_s: bigint;
    b16_s: bigint;
    a32_s: bigint;
    b32_s: bigint;
    a64_s: bigint;
    b64_s: bigint;
  };
}

export interface CheckedArithmeticWithOverflowBitTestsContractInterface
  extends Interface {
  getFunction(
    nameOrSignature:
      | "checkedAddWithOverflowBitTest"
      | "checkedMulWithOverflowBitTest"
      | "checkedSubWithOverflowBitTest"
      | "decryptAndCompareResults16"
      | "decryptAndCompareResults32"
      | "decryptAndCompareResults64"
      | "getAddResult"
      | "getMulResult"
      | "getSubResult"
      | "setPublicValues"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkedAddWithOverflowBitTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkedMulWithOverflowBitTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkedSubWithOverflowBitTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptAndCompareResults16",
    values: [CheckedArithmeticWithOverflowBitTestsContract.Check16Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptAndCompareResults32",
    values: [CheckedArithmeticWithOverflowBitTestsContract.Check32Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptAndCompareResults64",
    values: [CheckedArithmeticWithOverflowBitTestsContract.Check64Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMulResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPublicValues",
    values: [
      CheckedArithmeticWithOverflowBitTestsContract.AllGTCastingValuesStruct,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkedAddWithOverflowBitTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkedMulWithOverflowBitTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkedSubWithOverflowBitTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptAndCompareResults16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptAndCompareResults32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptAndCompareResults64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMulResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPublicValues",
    data: BytesLike
  ): Result;
}

export interface CheckedArithmeticWithOverflowBitTestsContract
  extends BaseContract {
  connect(
    runner?: ContractRunner | null
  ): CheckedArithmeticWithOverflowBitTestsContract;
  waitForDeployment(): Promise<this>;

  interface: CheckedArithmeticWithOverflowBitTestsContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkedAddWithOverflowBitTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  checkedMulWithOverflowBitTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  checkedSubWithOverflowBitTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  decryptAndCompareResults16: TypedContractMethod<
    [check16: CheckedArithmeticWithOverflowBitTestsContract.Check16Struct],
    [bigint],
    "nonpayable"
  >;

  decryptAndCompareResults32: TypedContractMethod<
    [check32: CheckedArithmeticWithOverflowBitTestsContract.Check32Struct],
    [bigint],
    "nonpayable"
  >;

  decryptAndCompareResults64: TypedContractMethod<
    [check64: CheckedArithmeticWithOverflowBitTestsContract.Check64Struct],
    [bigint],
    "nonpayable"
  >;

  getAddResult: TypedContractMethod<[], [bigint], "view">;

  getMulResult: TypedContractMethod<[], [bigint], "view">;

  getSubResult: TypedContractMethod<[], [bigint], "view">;

  setPublicValues: TypedContractMethod<
    [
      castingValues: CheckedArithmeticWithOverflowBitTestsContract.AllGTCastingValuesStruct,
      a: BigNumberish,
      b: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkedAddWithOverflowBitTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkedMulWithOverflowBitTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkedSubWithOverflowBitTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decryptAndCompareResults16"
  ): TypedContractMethod<
    [check16: CheckedArithmeticWithOverflowBitTestsContract.Check16Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decryptAndCompareResults32"
  ): TypedContractMethod<
    [check32: CheckedArithmeticWithOverflowBitTestsContract.Check32Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decryptAndCompareResults64"
  ): TypedContractMethod<
    [check64: CheckedArithmeticWithOverflowBitTestsContract.Check64Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAddResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMulResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setPublicValues"
  ): TypedContractMethod<
    [
      castingValues: CheckedArithmeticWithOverflowBitTestsContract.AllGTCastingValuesStruct,
      a: BigNumberish,
      b: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
