/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPrivateERC721URIStorage } from "./IPrivateERC721URIStorage";
export type { PrivateERC721URIStorage } from "./PrivateERC721URIStorage";
